In [1]:
import pandas as pd
import numpy as np

data = {'NAME': ["A"," B","C","A","D"], 'AGE': [25, 40 , 30, 25,60], 'SALARY': [50000,None,300000,50000,40000]}
df = pd.DataFrame(data)
df

  NAME  AGE    SALARY
0    A   25   50000.0
1    B   40       NaN
2    C   30  300000.0
3    A   25   50000.0
4    D   60   40000.0

In [2]:
 df.drop_duplicates()

  NAME  AGE    SALARY
0    A   25   50000.0
1    B   40       NaN
2    C   30  300000.0
4    D   60   40000.0

In [3]:
AVG = df['SALARY'].mean()
df['SALARY'].fillna(AVG, inplace=True)
df

/tmp/ipython-input-2948412171.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['SALARY'].fillna(AVG, inplace=True)

  NAME  AGE    SALARY
0    A   25   50000.0
1    B   40  110000.0
2    C   30  300000.0
3    A   25   50000.0
4    D   60   40000.0

In [4]:
df['SALARY'] = df['SALARY'].fillna(AVG)

In [6]:
df1 = pd.read_csv('/content/Dataset_with_ID_and_Name_First.csv')
df1.head()

  Employee_ID Employee_Name   Age   Salary  Experience      Score Department
0        E001    Diya Singh  58.0  97121.0        27.0  65.852354  Marketing
1        E002   Meera Patel  48.0  99479.0         3.0  56.012591    Finance
2        E003  Meera Sharma  34.0  49457.0         1.0        NaN         IT
3        E004   Aisha Mehta  27.0  96557.0         3.0  77.507859         HR
4        E005     Diya Iyer  40.0  82995.0         NaN  66.723748         IT

In [7]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Employee_ID    50 non-null     object
 1   Employee_Name  50 non-null     object
 2   Age            45 non-null     float64
 3   Salary         45 non-null     float64
 4   Experience     45 non-null     float64
 5   Score          45 non-null     float64
 6   Department     50 non-null     object
dtypes: float64(4), object(3)
memory usage: 2.9+ KB

In [8]:
df1.describe()

             Age        Salary  Experience      Score
count  45.000000     45.000000   45.000000  45.000000
mean   39.022222  65103.755556   14.911111  70.847343
std    11.754088  21865.529013    9.092510   9.647996
min    21.000000  31016.000000    1.000000  49.084003
25%    30.000000  42666.000000    7.000000  64.301717
50%    39.000000  68044.000000   14.000000  69.726236
75%    47.000000  82256.000000   23.000000  77.507859
max    59.000000  99479.000000   29.000000  91.587285

In [12]:
df1.drop_duplicates()

,Employee_ID,Employee_Name,Age,Salary,Experience,Score,Department
0,E001,Diya Singh,58.0,97121.0,27.0,65.852354,Marketing
1,E002,Meera Patel,48.0,99479.0,3.0,56.012591,Finance
2,E003,Meera Sharma,34.0,49457.0,1.0,NaN,IT
3,E004,Aisha Mehta,27.0,96557.0,3.0,77.507859,HR
4,E005,Diya Iyer,40.0,82995.0,NaN,66.723748,IT
5,E006,Riya Verma,58.0,70757.0,15.0,61.384019,Marketing
6,E007,Aarav Reddy,38.0,39692.0,14.0,67.418152,Finance
7,E008,Aisha Verma,NaN,75758.0,3.0,74.609556,Finance
8,E009,Aditya Sharma,30.0,NaN,1.0,56.506100,Operations
9,E010,Aarav Patel,30.0,NaN,5.0,59.809272,Finance
10,E011,Anaya Patel,43.0,62606.0,26.0,71.270122,Operations
11,E012,Aarav Sharma,55.0,41534.0,NaN,57.505563,HR
12,E013,Aisha Singh,59.0,70397.0,14.0,89.451156,Marketing
13,E014,Vivaan Patel,NaN,31016.0,7.0,68.466635,Operations
14,E015,Vivaan Patel,22.0,NaN,27.0,60.930128,HR
15,E016,Riya Sharma,41.0,53247.0,9.0,61.826458,Finance
16,E017,Meera Iyer,21.0,54300.0,15.0,65.168773,Finance
17,E018,Meera Singh,43.0,39268.0,15.0,64.301717,HR
18,E019,Meera Verma,49.0,42185.0,26.0,49.084003,Finance
19,E020,Aditya Chopra,57.0,93704.0,10.0,82.637405,HR
20,E021,Riya Reddy,21.0,69099.0,28.0,69.845167,Operations
21,E022,Meera Mehta,NaN,NaN,13.0,69.726236,Operations
22,E023,Vivaan Iyer,52.0,68044.0,19.0,78.178735,HR
23,E024,Diya Chopra,31.0,81214.0,7.0,NaN,Operations
24,E025,Anaya Chopra,41.0,91228.0,17.0,62.416729,Operations
25,E026,Diya Singh,44.0,NaN,20.0,74.574156,Operations
26,E027,Anaya Chopra,46.0,70774.0,29.0,69.356219,IT
27,E028,Aisha Patel,47.0,32568.0,4.0,73.449023,Marketing
28,E029,Aarav Patel,35.0,92592.0,5.0,69.199127,Finance
29,E030,Diya Verma,34.0,97563.0,23.0,67.586199,IT
30,E031,Aarav Bose,22.0,32695.0,7.0,84.335155,Operations
31,E032,Aisha Bose,56.0,78190.0,13.0,80.657937,HR
32,E033,Anaya Sharma,26.0,35258.0,15.0,NaN,Operations
33,E034,Riya Bose,40.0,69504.0,NaN,84.803286,Marketing
34,E035,Kabir Patel,28.0,63159.0,29.0,91.587285,Operations
35,E036,Kabir Sharma,58.0,43986.0,NaN,82.317784,HR
36,E037,Aarav Reddy,37.0,91858.0,13.0,NaN,Marketing
37,E038,Kabir Kapoor,23.0,42666.0,7.0,63.108058,Operations
38,E039,Aditya Sharma,44.0,68660.0,27.0,77.278331,Marketing
39,E040,Diya Chopra,33.0,33561.0,19.0,63.809306,Finance
40,E041,Aditya Chopra,28.0,56854.0,22.0,73.561598,Finance
41,E042,Riya Reddy,NaN,94505.0,28.0,69.781191,Operations
42,E043,Aditya Singh,21.0,82251.0,2.0,82.180504,Marketing
43,E044,Anaya Mehta,39.0,52662.0,10.0,NaN,HR
44,E045,Aditya Chopra,47.0,38392.0,13.0,65.571977,Operations
45,E046,Diya Mehta,NaN,60535.0,25.0,73.782266,Finance
46,E047,Diya Mehta,27.0,82256.0,21.0,89.338398,Finance
47,E048,Riya Chopra,54.0,65222.0,6.0,70.809708,Operations
48,E049,Riya Mehta,33.0,93335.0,NaN,65.835436,Marketing
49,E050,Meera Singh,36.0,40965.0,28.0,78.575033,Finance

In [13]:
df1.isnull().sum()

Employee_ID      0
Employee_Name    0
Age              5
Salary           5
Experience       5
Score            5
Department       0
dtype: int64

In [16]:
numeric_cols = ['Age', 'Salary', 'Experience', 'Score']
df1[numeric_cols] = df1[numeric_cols].fillna(df1[numeric_cols].median())
df1.isnull().sum()

Employee_ID      0
Employee_Name    0
Age              0
Salary           0
Experience       0
Score            0
Department       0
dtype: int64

In [19]:
for col in numeric_cols:
    df1[col + '_zscore'] = (df1[col] - df1[col].mean()) / df1[col].std()

display(df1.head())

,Employee_ID,Employee_Name,Age,Salary,Experience,Score,Department,Age_zscore,Salary_zscore,Experience_zscore,Score_zscore
0,E001,Diya Singh,58.0,97121.0,27.0,65.852354,Marketing,1.704036,1.529635,1.412903,-0.533717
1,E002,Meera Patel,48.0,99479.0,3.0,56.012591,Finance,0.806230,1.643333,-1.371142,-1.609239
2,E003,Meera Sharma,34.0,49457.0,1.0,69.726236,IT,-0.450699,-0.768635,-1.603146,-0.110287
3,E004,Aisha Mehta,27.0,96557.0,3.0,77.507859,HR,-1.079163,1.502440,-1.371142,0.740273
4,E005,Diya Iyer,40.0,82995.0,14.0,66.723748,IT,0.087985,0.848505,-0.095122,-0.438470

In [22]:
from sklearn.preprocessing import MinMaxScaler, RobustScaler, StandardScaler

# Initialize scalers
min_max_scaler = MinMaxScaler()
robust_scaler = RobustScaler()
standard_scaler = StandardScaler()


df_minmax = pd.DataFrame(min_max_scaler.fit_transform(df1[numeric_cols]), columns=[col+'_minmax' for col in numeric_cols])
df_robust = pd.DataFrame(robust_scaler.fit_transform(df1[numeric_cols]), columns=[col+'_robust' for col in numeric_cols])
df_standard = pd.DataFrame(standard_scaler.fit_transform(df1[numeric_cols]), columns=[col+'_standard' for col in numeric_cols])

print("\nMin-Max Scaled Data (first 5 rows):\n", df_minmax.head())
print("\nStandard Scaled Data (first 5 rows):\n", df_standard.head())
print("\nRobust Scaled Data (first 5 rows):\n", df_robust.head())

Min-Max Scaled Data (first 5 rows):
    Age_minmax  Salary_minmax  Experience_minmax  Score_minmax
0    0.973684       0.965558           0.928571      0.394519
1    0.710526       1.000000           0.071429      0.163013
2    0.342105       0.269357           0.000000      0.485662
3    0.157895       0.957320           0.071429      0.668745
4    0.500000       0.759228           0.464286      0.415021

Standard Scaled Data (first 5 rows):
    Age_standard  Salary_standard  Experience_standard  Score_standard
0      1.721337         1.545165             1.427247       -0.539135
1      0.814415         1.660017            -1.385063       -1.625577
2     -0.455275        -0.776438            -1.619422       -0.111407
3     -1.090120         1.517693            -1.385063        0.747789
4      0.088878         0.857120            -0.096087       -0.442922

Robust Scaled Data (first 5 rows):
    Age_robust  Salary_robust  Experience_robust  Score_robust
0    1.151515       0.793630           0.881356     -0.341565
1    0.545455       0.857989          -0.745763     -1.209149
2   -0.303030      -0.507315          -0.881356      0.000000
3   -0.727273       0.778236          -0.745763      0.686116
4    0.060606       0.408074           0.000000     -0.264733

In [24]:
# Central Tendency and Dispersion
central_dispersion = {
    'Mean': df1[numeric_cols].mean(),
    'Median': df1[numeric_cols].median(),
    'Mode': df1[numeric_cols].mode().iloc[0],
    'Std Dev': df1[numeric_cols].std(),
    'Variance': df1[numeric_cols].var(),
    'Range': df1[numeric_cols].max() - df1[numeric_cols].min(),
    'IQR': df1[numeric_cols].quantile(0.75) - df1[numeric_cols].quantile(0.25)
}
central_dispersion_df = pd.DataFrame(central_dispersion)
print("\nCentral Tendency and Dispersion:\n", central_dispersion_df)

Central Tendency and Dispersion:
                     Mean        Median          Mode       Std Dev  \
Age            39.020000     39.000000     39.000000     11.138259
Salary      65397.780000  68044.000000  68044.000000  20739.079971
Experience     14.820000     14.000000     14.000000      8.620550
Score          70.735233     69.726236     69.726236      9.148820

                Variance         Range           IQR
Age         1.240608e+02     38.000000     16.500000
Salary      4.301094e+08  68463.000000  36638.000000
Experience  7.431388e+01     28.000000     14.750000
Score       8.370091e+01     42.503282     11.341563